spec:
  template:
    spec:
      containers:
      - name: athenz-zts-server
        env:
        - name: USER_CLASSPATH
          value: "/opt/athenz/zts/lib/jars/*:/usr/lib/jars/*:/athenz/plugins/*"
        volumeMounts:
        - name: providers-json-vol
          mountPath: /opt/athenz/zts/conf/providers.json
          subPath: providers.json
      volumes:
      - name: providers-json-vol
        configMap:
          name: zts-providers-config
